
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - dev

resources:
- repo: self

variables:
  imageName: '600feet'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  registryName: 'demodrw0.azurecr.io'

stages:
- stage: BuildAndPackage
  displayName: BuildAndPackage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(dockerfilePath)'
#        tags: |
#          $(imageName)

          # Docker
    - task: Docker@2
      inputs:
        containerRegistry: 'TLGDockerServiceConnection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
#    - script: |
#        docker save $(imageName) -o $(Build.ArtifactStagingDirectory)/image.tar
#      displayName: 'Save Docker image as .tar file'
#    - task: PublishBuildArtifacts@1
#      inputs:
#        PathtoPublish: '$(Build.ArtifactStagingDirectory)/image.tar'
#        ArtifactName: 'drop'
#        publishLocation: 'Container'

